# Generated by Django 5.1.4 on 2025-01-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendations_user_alter_restaurant_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
